-- =========================================================
-- tuSanatorio
-- PostgreSQL
-- =========================================================

-- =========================================================
-- 1. ROLES
-- =========================================================

CREATE TABLE Roles (
    rol_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol VARCHAR(50) NOT NULL
);


-- =========================================================
-- 2. ESPECIALIDADES
-- =========================================================

CREATE TABLE Especialidades (
    id_especialidad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);


-- =========================================================
-- 3. USUARIOS
-- =========================================================

CREATE TABLE Usuarios (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    DNI BIGINT NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(200) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    telefono VARCHAR(20) NOT NULL UNIQUE,
    id_rol INT NOT NULL,

    CONSTRAINT FK_Usuarios_Roles
        FOREIGN KEY (id_rol)
        REFERENCES Roles(rol_id)
);


-- =========================================================
-- 4. MEDICOS
-- =========================================================

CREATE TABLE Medicos (
    id_medico INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL,
    id_especialidad INT NOT NULL,

    CONSTRAINT FK_Medicos_Usuarios
        FOREIGN KEY (id_usuario)
        REFERENCES Usuarios(id_usuario),

    CONSTRAINT FK_Medicos_Especialidades
        FOREIGN KEY (id_especialidad)
        REFERENCES Especialidades(id_especialidad)
);


-- =========================================================
-- 5. PACIENTES
-- =========================================================

CREATE TABLE Pacientes (
    id_paciente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL,

    CONSTRAINT FK_Pacientes_Usuarios
        FOREIGN KEY (id_usuario)
        REFERENCES Usuarios(id_usuario)
);


-- =========================================================
-- 6. OBRAS SOCIALES
-- =========================================================

CREATE TABLE Obras_sociales (
    id_obra_social INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obra_social VARCHAR(100) NOT NULL
);


-- =========================================================
-- 7. PACIENTES - OBRAS SOCIALES
-- =========================================================

CREATE TABLE Pacientes_ObrasSociales (
    id_paciente_obras INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INT NOT NULL,
    id_obra_social INT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_Paciente
        FOREIGN KEY (id_paciente)
        REFERENCES Pacientes(id_paciente),

    CONSTRAINT FK_ObraSocialPaciente
        FOREIGN KEY (id_obra_social)
        REFERENCES Obras_sociales(id_obra_social),

    CONSTRAINT UQ_Paciente_Obra
        UNIQUE (id_paciente, id_obra_social)
);


-- =========================================================
-- 8. MEDICOS - OBRAS SOCIALES
-- =========================================================

CREATE TABLE Medicos_ObrasSociales (
    id_medico_obras INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_medico INT NOT NULL,
    id_obra_social INT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_Medico
        FOREIGN KEY (id_medico)
        REFERENCES Medicos(id_medico),

    CONSTRAINT FK_ObraSocialMedico
        FOREIGN KEY (id_obra_social)
        REFERENCES Obras_sociales(id_obra_social),

    CONSTRAINT UQ_Medico_Obra
        UNIQUE (id_medico, id_obra_social)
);


-- =========================================================
-- 9. RANGOS
-- =========================================================

CREATE TABLE Rangos (
    id_rango INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL
);


-- =========================================================
-- 10. TURNOS DISPONIBLES
-- =========================================================

CREATE TABLE Turnos_disponibles (
    id_turno INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_medico INT NOT NULL,
    id_rango INT NOT NULL,
    fecha_turno DATE NOT NULL,

    CONSTRAINT FK_TurnosDisponibles_Medicos
        FOREIGN KEY (id_medico)
        REFERENCES Medicos(id_medico),

    CONSTRAINT FK_TurnosDisponibles_Rangos
        FOREIGN KEY (id_rango)
        REFERENCES Rangos(id_rango)
);


-- =========================================================
-- 11. TURNOS ASIGNADOS
-- =========================================================

CREATE TABLE Turnos_asignados (
    id_turno_asignado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_turno INT NOT NULL,
    id_paciente INT NOT NULL,
    id_obra_social INT NOT NULL,
    fecha_asignacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_TurnosAsignados_Turno
        FOREIGN KEY (id_turno)
        REFERENCES Turnos_disponibles(id_turno)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,

    CONSTRAINT FK_TurnosAsignados_Paciente
        FOREIGN KEY (id_paciente)
        REFERENCES Pacientes(id_paciente)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_TurnosAsignados_ObraSocial
        FOREIGN KEY (id_obra_social)
        REFERENCES Obras_sociales(id_obra_social)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);


-- =========================================================
-- 12. TURNOS DESCARTADOS
-- =========================================================

CREATE TABLE TurnosDescartados (
    id_turno INT PRIMARY KEY,
    id_medico INT NOT NULL,
    id_rango INT NOT NULL,
    fecha_turno DATE NOT NULL
);


-- =========================================================
-- 13. TURNOS HISTORICOS
-- =========================================================

CREATE TABLE TurnosHistoricos (
    id_turno_asignado INT PRIMARY KEY,
    id_turno INT NOT NULL,
    id_paciente INT NOT NULL,
    id_obra_social INT,
    fecha_asignacion TIMESTAMP NOT NULL
);


-- =========================================================
-- 14. MEDIO DE PAGO
-- =========================================================

CREATE TABLE Medio_pago (
    id_medio_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio_pago VARCHAR(50) NOT NULL
);


-- =========================================================
-- 15. PAGOS
-- =========================================================

CREATE TABLE Pagos (
    id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_turno_asignado INT NOT NULL,
    id_medio_pago INT NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    fecha_pago TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_Pagos_TurnoAsignado
        FOREIGN KEY (id_turno_asignado)
        REFERENCES Turnos_asignados(id_turno_asignado),

    CONSTRAINT FK_Pagos_MedioPago
        FOREIGN KEY (id_medio_pago)
        REFERENCES Medio_pago(id_medio_pago)
);


-- =========================================================
-- 16. HISTORIAS CLINICAS
-- =========================================================

CREATE TABLE HistClinicas (
    id_historia_clinica INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_HistClinicas_Paciente
        FOREIGN KEY (id_paciente)
        REFERENCES Pacientes(id_paciente)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


-- =========================================================
-- 17. DETALLE HISTORIAS
-- =========================================================

CREATE TABLE Detalle_Historias (
    id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_historia_clinica INT NOT NULL,
    id_medico INT NOT NULL,
    historia_clinica TEXT NOT NULL,
    fecha_detalle TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DetalleHistorias_Historia
        FOREIGN KEY (id_historia_clinica)
        REFERENCES HistClinicas(id_historia_clinica)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_DetalleHistorias_Medico
        FOREIGN KEY (id_medico)
        REFERENCES Medicos(id_medico)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);